/* Generated from the files in instruments/ by tools/txt2c.py: the instruments built in (a stick's INSTR folder adds to them). */
#include "inst.h"

const struct inst_text inst_builtin[] = {
  { "GRIDPADS.TXT",
    "# GRIDPADS: sixteen pads on a minor pentatonic scale, GENDY's walking waves, an arpeggio under the held pads.\n"
    "\n"
    "name: GRIDPADS\n"
    "by: BARE!\n"
    "about: 4x4 pads on a minor pentatonic scale, arpeggiated\n"
    "\n"
    "[sound]\n"
    "wave: gendy1\n"
    "attack: 3\n"
    "decay: 250\n"
    "sustain: 40\n"
    "release: 200\n"
    "cutoff: 96\n"
    "resonance: 30\n"
    "envelope: 20\n"
    "level: 75\n"
    "\n"
    "[play]\n"
    "pads: 4x4 C3\n"
    "scale: minorpenta\n"
    "keys: scale C3\n"
    "arp: up\n"
    "rate: 4\n"
    "octaves: 2\n"
    "\n"
    "[knobs]\n"
    "knobs: cutoff resonance envelope decay rate level\n" },
  { "SHRUTI.TXT",
    "# SHRUTI: a shruti box, the drone box of Indian music. The keys open its reeds (a key opens one, pressed again it\n"
    "# closes), and the air comes from the bellows: move a finger to and fro on the touchpad, or hold Enter. The reeds are\n"
    "# tuned in just intonation from Sa, the keys' first note (Z): Pa (B) is exactly 3:2 above it, Ma (V) 4:3.\n"
    "# Sa is C here; for another, change the note after \"chromatic\".\n"
    "\n"
    "name: SHRUTI\n"
    "by: BARE!\n"
    "about: a drone box: the keys open reeds, the touchpad is its bellows\n"
    "\n"
    "[sound]\n"
    "wave: pulse\n"
    "width: 22\n"
    "detune: 8\n"
    "attack: 160\n"
    "sustain: 100\n"
    "release: 500\n"
    "cutoff: 92\n"
    "resonance: 18\n"
    "level: 62\n"
    "\n"
    "[play]\n"
    "keys: chromatic C3\n"
    "tuning: just\n"
    "hold: toggle\n"
    "bellows: yes\n"
    "\n"
    "[knobs]\n"
    "knobs: width detune cutoff resonance attack release level\n" },
  { "SIEVHARP.TXT",
    "# SIEVEHARP: a harp tuned to a sieve (S1 on the XENAKIS page's SIEVES view): the letter rows play its steps upward,\n"
    "# and held notes fall down it at random. Change S1, and the harp is retuned.\n"
    "\n"
    "name: SIEVHARP\n"
    "by: BARE!\n"
    "about: a harp tuned to sieve S1, falling at random\n"
    "\n"
    "[sound]\n"
    "wave: tri\n"
    "attack: 1\n"
    "decay: 700\n"
    "sustain: 0\n"
    "release: 400\n"
    "cutoff: 110\n"
    "level: 80\n"
    "\n"
    "[play]\n"
    "keys: scale C3\n"
    "scale: S1\n"
    "arp: random\n"
    "rate: 3\n"
    "octaves: 1\n"
    "hold: yes\n"
    "\n"
    "[knobs]\n"
    "knobs: decay release rate level\n" },
  { "STYLO.TXT",
    "# STYLO: a pocket organ played with a stylus on a metal strip, after the Stylophone (1967).\n"
    "# The touchpad is the strip: 20 notes from A2, one at a time, a new note each time the finger crosses a key.\n"
    "\n"
    "name: STYLO\n"
    "by: BARE!\n"
    "about: a stylus on a metal strip: the touchpad is the strip\n"
    "\n"
    "[sound]\n"
    "wave: pulse\n"
    "width: 30\n"
    "attack: 1\n"
    "decay: 1\n"
    "sustain: 100\n"
    "release: 15\n"
    "cutoff: 100\n"
    "vibrato: 0\n"
    "level: 65\n"
    "\n"
    "[play]\n"
    "strip: A2 E4\n"
    "steps: semitones\n"
    "keys: chromatic A2\n"
    "mono: yes\n"
    "\n"
    "[knobs]\n"
    "knobs: width cutoff vibrato release level\n" },
  { "THEREMIN.TXT",
    "# THEREMIN: pitch without steps. Across the touchpad is the pitch, as smooth as the finger; pressing harder is louder.\n"
    "\n"
    "name: THEREMIN\n"
    "by: BARE!\n"
    "about: across the touchpad, pitch without steps; pressure, loudness\n"
    "\n"
    "[sound]\n"
    "wave: sine\n"
    "attack: 80\n"
    "decay: 10\n"
    "sustain: 100\n"
    "release: 300\n"
    "vibrato: 25\n"
    "level: 80\n"
    "\n"
    "[play]\n"
    "strip: C3 C6\n"
    "steps: free\n"
    "glide: 40\n"
    "mono: yes\n"
    "\n"
    "[knobs]\n"
    "knobs: vibrato glide attack release level\n" },
};
const int inst_builtin_count = (int)(sizeof inst_builtin / sizeof inst_builtin[0]);
